<ul class="sidebar-menu" data-widget="tree">
    @role('administrator')
        @include('sidebar/kontrolpanel')
    @endrole
    @role(['accounting'])
        @include('sidebar/accounting')
    @endrole
    @role(['rekammedis'])
        @include('sidebar/frontoffice')
    @endrole
    @role(['supervisor'])
        @include('sidebar/supervisor')
    @endrole
    @role(['emr'])
        @include('sidebar/emr')
    @endrole
    @role(['emr_igd'])
        @include('sidebar/emr_igd')
    @endrole
    @role(['emr_inap'])
        @include('sidebar/emr_inap')
    @endrole

    @role(['costing'])
        @include('sidebar/costing')
    @endrole
    @role(['loketigd'])
        @include('sidebar/loketIGD')
    @endrole
    @role(['tracer'])
        @include('sidebar/tracer')
    @endrole
    @role(['outguide'])
        @include('sidebar/outguide')
    @endrole
    @role(['admission'])
        @include('sidebar/tppri')
    @endrole
    @role(['sisrute'])
        @include('sidebar/sisrute')
    @endrole

    @role(['antrian'])
        @include('sidebar/antrian')
    @endrole
    @role(['rawatdarurat'])
        @include('sidebar/igd')
    @endrole
    @role(['rawatjalan'])
        @include('sidebar/rawatjalan')
    @endrole
    @role(['laboratorium_patalogi_anatomi'])
        @include('sidebar/laboratoriumCommon')
    @endrole
    @role(['laboratorium'])
        @include('sidebar/laboratorium')
    @endrole
    @role(['bdrs'])
        @include('sidebar/bdrs')
    @endrole
    @role(['radiologi'])
        @include('sidebar/radiologi')
        {{-- @include('sidebar/radiologi_gigi') --}}
    @endrole
    @role(['radiologi-gigi'])
        @include('sidebar/radiologi_gigi')
    @endrole
    @role(['echodiagram'])
        @include('sidebar/echocardiograms')
    @endrole
    @role(['apotik'])
        @include('sidebar/farmasi')
    @endrole
    @role(['antrianfarmasi'])
        @include('sidebar/antrianfarmasi')
    @endrole

    @role(['kasir'])
        @include('sidebar/kasir')
    @endrole
    @role(['operasi'])
        @include('sidebar/operasi')
    @endrole
    @role(['emr_operasi'])
        @include('sidebar/emr-operasi')
    @endrole
    @role(['display'])
        @include('sidebar/informasi')
        @include('sidebar/displaytempattidur')
    @endrole
    @role(['fisioterapis'])
        @include('sidebar/fisioterapi')
    @endrole
    @role(['gizi'])
        @include('sidebar/gizi')
    @endrole
    @role(['cetak'])
        @include('sidebar/cetak')
    @endrole
    @role(['verifikator'])
        @include('sidebar/verifikator')
    @endrole
    @role(['rehabmedik'])
        @include('sidebar/rehabmedik')
    @endrole
    @role(['bpjs'])
        @include('sidebar/bpjs')
    @endrole
    @role(['logistikmedik'])
        @include('sidebar/logistikmedik')
    @endrole
    @role(['verifikatorlogistik'])
        @include('sidebar/verifikatorlogistik')
    @endrole
    @role(['nonmedis'])
        @include('sidebar/logistiknonmedik')
    @endrole
    @role(['pimpinan'])
        @include('sidebar/direksi')
    @endrole
    @role(['rawatinap'])
        @include('sidebar/rawatinap')
    @endrole
    @role('hemodialisa')
        @include('sidebar/hemodialisa')
    @endrole
    @role(['jenazah', 'ambulans'])
        @include('sidebar/pemulasaran_jenazah')
    @endrole
    @role(['protesagigi'])
        @include('sidebar/protesagigi')
    @endrole
    @role('kepegawaian')
        @include('sidebar/hrd')
    @endrole
    @role(['sirsv6'])
        @include('sidebar/sirs')
        {{-- @include('sidebar/ambulans') --}}
    @endrole
    @role('parkir')
        @include('sidebar/parkir')
    @endrole
    @role('ppi')
        @include('sidebar/ppi')
    @endrole
    @role('android')
        @include('sidebar/android')
    @endrole

    @role('saderek')
        @include('sidebar/saderek')
    @endrole
    {{-- @include('sidebar/medikal-checkup') nanti --}}
    @role('rekammedik')
        @include('sidebar/rekammedik')
    @endrole
    @role('sipeka')
        @include('sidebar/sipeka')
    @endrole
    @role('satusehat')
        @include('sidebar/satusehat')
    @endrole
    @role('esign')
        @include('sidebar/esign')
    @endrole
    @role('log')
        @include('sidebar/log')
    @endrole
    {{-- @include('sidebar/mobilisasi-dana') nanti --}}
    {{-- @include('sidebar/akuntasi') nanti --}}
    {{-- @include('sidebar/logistiknonmedik') nanti --}}
    {{-- @include('sidebar/jurnal-jkn') nanti --}}
    {{-- @include('sidebar/smsgateway') nanti --}}
</ul>
